version = 3.11.0
runner.dialect = scala3

maxColumn = 120
align.openParenCallSite = true
align.openParenDefnSite = true
continuationIndent.defnSite = 2
assumeStandardLibraryStripMargin = true
danglingParentheses.preset = true

rewrite.rules = [AvoidInfix, SortImports, RedundantParens, SortModifiers]
rewrite.scala3.convertToNewSyntax = true

docstrings = JavaDoc
docstrings.style = keep
docstrings.oneline = unfold

newlines.afterCurlyLambda = preserve

fileOverride {
  "glob:**/*.sbt" {
    runner.dialect = sbt1
  }
}
